### ISSUE TITLE
Statically set `service.name` to `github.actions`

### ISSUE THREAD

**Issue by nikordaris** [inception-health/otel-export-trace-action#168]
In honeycomb, datasets are created based on the `service.name` attribute. Currently, we are setting this to the workflow name which creates a new dataset for each workflow. This creates issues with using honeycomb across all your workflows. So instead we should treat the service as a singular entity, which it is, and hardcode that to `github.actions`

**Comment by nikordaris** [comment]
Use `otelServiceName` input arg to set the service name to a static value such as `github.actions` https://github.com/inception-health/otel-export-trace-action#action-inputs

**Comment by gerhard** [comment]
This was helpful, thank you!
