### ISSUE TITLE
Don't include trace spans for skipped or canceled steps in jobs

### ISSUE THREAD

**Issue by seh** [inception-health/otel-export-trace-action#31]
At present, this action publishes a trace span for all steps in each job that it covers, whether or not the steps actually ran. For steps in a job that get skipped, we should not publish trace spans representing them, as there was no actual work that occurred.

We can detect which steps were skipped by checking [the "outcome" field of the "steps" context](https://docs.github.com/en/actions/learn-github-actions/contexts#steps-context). If the value is "cancelled" or "skipped," then the step never ran. We should only include trace spans for steps whose outcome is "success" or "failure."

It looks like we could add this guard condition to [the `traceWorkflowRunStep` function](https://github.com/inception-health/otel-export-trace-action/blob/0da4af935b980e5d19b8b8a6afd8c29d26b21e2c/src/tracing/step.ts#L20-L75).

**Comment by nikordaris** [comment]
This seems like a reasonable enhancement. That location looks good to add the check. Happy to review a PR and get a release cut with this change.

**Comment by seh** [comment]
I wrote a patch to implement this change, but I am uncertain of how best to test it. Would you like me to post it if I'm not sure yet whether it works as intended?

**Comment by seh** [comment]
Please see #33 for this improvement.
