### ISSUE TITLE
Feature suggestion: Consider adding `trace.trace_id` as an output

### ISSUE THREAD

**Issue by bixu** [inception-health/otel-export-trace-action#4]
This would be helpful for other automation, like generating links to Honeycomb trace views.

**Comment by nikordaris** [comment]
You can get the traceId from `rootSpan.spanContext().traceId` from [tracing.ts](https://github.com/inception-health/otel-export-trace-action/blob/main/src/tracing.ts#L117). We'll want to define Output inside of [runner.ts](https://github.com/inception-health/otel-export-trace-action/blob/main/src/runner.ts#L32) though. so i think we can just return the `SpanContext` from `traceWorkflowRunJobs`.
